# -*- encoding : utf-8 -*-
require 'httparty'
require 'httparty/request'
require 'httparty/response/headers'
require 'rspec'
require 'cucumber'
require 'pry'
require 'test-unit'
require 'aspector'
require 'openssl'
require 'open-uri'
require 'faker'
require 'cpf_faker'
require 'report_builder'